### ISSUE TITLE
What is each branch for?

### ISSUE THREAD

**Issue by ianeinser** [rubykube/mockserver#7]
Hi.. there are some branches. May i know what each branch for?

For instance master branch and v2 branch. Do you plan to merge them?

**Comment by calj** [comment]
We used to support peatio v2 api in this branch but now everything is in master, in different folders served on different ports.
Here are the defaults:

- v1 API mockserver runs on port 9001
- v2 API mockserver runs on port 9002
- Slanger mock runs on port 9010
- Ranger mock runs on port 9011
